server:
  port: 1200
  servlet:
    context-path: /tasty-town

spring:
  datasource:
    url: jdbc:mysql://localhost/tasty-town
    username: root
    password: dhananjaya@1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

upload:
  file:
    dir: images